---
- name: Using new module
  hosts: localhost

  tasks:
          - name: New mod
            my_new_test_module:
                    name: fail me 
            register: results

          - debug:
                  var: results.message
